### ISSUE TITLE
Crash on running base.py

### ISSUE THREAD

**Issue by Candunc** [PlaceDevs/place-scraper#1]
```
Traceback (most recent call last):
  File "base.py", line 154, in <module>
    main()
  File "base.py", line 150, in main
    scraper.scrape_websocket_forever('place.sqlite')
  File "base.py", line 19, in scrape_websocket_forever
    self.ws = create_connection(url)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.4/dist-packages/websocket/_http.py", line 71, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_http.py", line 108, in _open_socket
    sock.setsockopt(*opts)
OSError: [Errno 22] Invalid argument
```

I've installed placescraper and websocket-client from pip3 and am running the latest place-scraper commit.

**Comment by danthedaniel** [comment]
What version of `websocket-client` are  you running?

Can you also tell me how you're invoking the scraper?

**Comment by Candunc** [comment]
0.40.0 is the version pip3 installed

Edit: I'm using the following command to invoke the scraper

    python3 base.py

**Comment by Candunc** [comment]
I've installed python3 on another computer and it is working. Thank you for your help regardless

**Comment by danthedaniel** [comment]
I can't replicate your issue on Python 3.4.2 and with websocket-client 0.40.

What OS are you running?

**Comment by danthedaniel** [comment]
I've only tested it on Linux, Debian 8 specifically.

**Comment by odensc** [comment]
I'm going to close this issue because you've figured it out. If we get another report we'll take a look into it.

**Comment by odensc** [comment]
Reopening, someone else has reported in Discord.
